services:
  - type: web
    name: singularity-backend
    env: node
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: SESSION_SECRET
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: singularity-db
          property: connectionString
      - key: DB_USER
        fromDatabase:
          name: singularity-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: singularity-db
          property: password
      - key: DB_HOST
        fromDatabase:
          name: singularity-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: singularity-db
          property: port
      - key: DB_DB
        fromDatabase:
          name: singularity-db
          property: database

databases:
  - name: singularity-db
    databaseName: singularity
    user: singularity_user
    plan: free